# Databricks Notebook DevOps Pipeline
## Expects two variables defined: DBR_WORKSPACE_URL, DBR_ACCESS_TOKEN
variables:
- group: AMLDBRVariables

# specific path build
trigger:
  branches:
    include:
    - main
    - releases/*
  paths:
    include:
    - databricks/*

pool:
  # This VM Image is recommended for Databricks deployment extension
  vmImage: 'ubuntu-16.04'

stages:
- stage: BuildMLSourceAssets
  jobs:
  - job: BuildDatabricks
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          addToPath: true
          architecture: 'x64'
      - task: Bash@3
        displayName: 'Install Testing Requirements'
        inputs:
          targetType: 'inline'
          script: 'pip install databricks-test spark-testing-base pyspark'
      
      - script: |
          pip install pytest
          pip install pytest-cov
          pytest ./databricks/tests --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
        displayName: 'Test with pytest'
      

- stage: DeployToTest
  jobs:
  - job: DeployDatabricksNotebooks
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          addToPath: true
          architecture: 'x64'
      - task: configuredatabricks@0
        inputs:
          url: '$(DBR_WORKSPACE_URL)'
          token: '$(DBR_ACCESS_TOKEN)'
      - task: deploynotebooks@0
        inputs:
          notebooksFolderPath: '$(System.DefaultWorkingDirectory)/databricks/notebooks'
          # TODO: Make this dynamic
          workspaceFolder: '/Shared/DemoApp'
