# https://aka.ms/MLOps

variables:
- group: mlops
- name: ml-ws-connection
  value: 'azmldemows' # Workspace Service Connection name


trigger: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo 'Working with...'
      echo $MODEL_ID
      ls -R
      echo '==========='
      echo "ml-path: $ML_PATH"
      echo '==========='
      ls -R $ML_PATH
- task: AzureCLI@2
  displayName: 'Install AML CLI'
  inputs:
    azureSubscription: $(ml-ws-connection)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az extension add -n azure-cli-ml'

- task: AzureCLI@2
  displayName: 'Attach folder to workspace'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az ml folder attach -w $(ml-ws) -g $(ml-rg)'

- task: AzureCLI@2
  displayName: 'Deploy model to ACI for QA'
  inputs:
    azureSubscription: $(ml-ws-connection)
    workingDirectory: $(ml-path)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az ml model deploy -n my-sklearn-qa-aci -m $MODEL_ID --ic ml/config-templates/inference-config.json --dc ml/config-templates/deployment-config-aci.json --overwrite'


# - task: AzureCLI@2
#   displayName: 'Deploy model to AKS for Production'
#   inputs:
#     azureSubscription: $(ml-ws-connection)
#     workingDirectory: $(ml-path)
#     scriptLocation: inlineScript
#     scriptType: 'bash'
#     inlineScript: 'az ml model deploy --name my-sklearn-prod-aks --ct $(ml-aks-name) -m $MODEL_ID --ic devops/inference-config.json --dc devops/deployment-config-aks.json  --overwrite'
